[package]
name = "binary_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_access = "0.1.9"
library_project = { version = "0.1.0", path = "../library_project" }
